## THIS FILE IS GITIGNORED FOR SECURITY REASONS FOR NOW
services: 

  express-app:
    build: .
    # image: mschmidty/deploy_test_server_express-app
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000 #Not really necessary!!! Just for example.
    depends_on: 
      - "postgres-db"
    restart: always
    # env_file:
    #   - ./.env # Use this if you want to actually use a file for env variables.
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - "express-app"
    restart: always



  postgres-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=mschmidty
      - POSTGRES_PASSWORD=mycatfatfred
      - POSTGRES_DB=deploy_test
    volumes:
      - postgres-test-db:/var/lib/postgresql/data

volumes:
  postgres-test-db: